ITNFA-19: Added possibility to redirect to the patient page if the patient already exists
IsantePlus/openmrs-module-registrationapp pull request #6
Opened 2018-03-13 16:47 UTC by dserkowski

2018-03-13 16:51 UTC, dserkowski commented
Before this, [the PR in M2Sys](https://github.com/IsantePlus/openmrs-module-m2sys-biometrics/pull/11) should be merged

2018-03-13 16:59 UTC, pgesek requested changes

2018-03-13 16:59 UTC, pgesek commented on api/src/main/resources/messages_fr.properties
> +registrationapp.biometrics.m2sys.register.alreadyExists.importingQuestion.label=Patient already exists
Can you email Nathaelf for translations?

2018-03-13 16:59 UTC, pgesek commented on omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/field/FingerprintM2sysFragmentController.java
> +                response.put("patientUuid", patient.getUuid());
bad identation

2018-03-13 16:59 UTC, pgesek commented on omod/src/main/webapp/resources/scripts/field/fingerprintM2sys.js
> +                m2SysError('Fingerprints already registered, you cannot register the same fingerprints again!');
can we use i18n for this?

2018-03-20 12:56 UTC, pawelcieszko approved these changes

2018-03-20 21:59 UTC, pawelcieszko approved these changes

2018-03-20 21:59 UTC, merged